package qr

import (
	"go3270/emulator/consts"
	"go3270/emulator/stream"
)

type CharacterSets struct {
	SFID  consts.SFID
	QCode consts.QCode
	Flag1 byte
	Flag2 byte
	SDW   byte
	SDH   byte
}

func NewCharacterSets() CharacterSets {
	return CharacterSets{
		SFID:  consts.QUERY_REPLY,
		QCode: consts.CHARACTER_SETS,
		Flag1: 0b00000000,
		Flag2: 0b00000000,
		// TODO 🔥 just copied these numbers from x3270
		SDW: 0x09,
		SDH: 0x0C,
	}
}

func (s CharacterSets) Put(in *stream.Inbound) {
	bytes := []byte{
		byte(s.SFID),
		byte(s.QCode),
	}
	// 👇 flags indicating basic support
	bytes = append(bytes, s.Flag1)
	bytes = append(bytes, s.Flag2)
	bytes = append(bytes, s.SDW)
	bytes = append(bytes, s.SDH)
	// TODO 🔥 this extra is generated by x3270???
	// 00 00 00 00 07 00 10 00 02 B9 00 25 01 00 F1 03 C3 01 36
	xtra := []byte{0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x10, 0x00, 0x02, 0xB9, 0x00, 0x25, 0x01, 0x00, 0xF1, 0x03, 0xC3, 0x01, 0x36}
	bytes = append(bytes, xtra...)
	in.Put16(uint16(len(bytes) + 2))
	in.PutSlice(bytes)
}
