package qr

import (
	"go3270/emulator/stream"
	"go3270/emulator/types"
)

// 🟧 Query Reply structured field

type CharacterSets struct {
	SFID  types.SFID
	QCode types.QCode
	Flag1 byte
	Flag2 byte
	SDW   byte
	SDH   byte
}

// 🟦 Constructor

func NewCharacterSets() CharacterSets {
	return CharacterSets{
		SFID:  types.QUERY_REPLY,
		QCode: types.CHARACTER_SETS,
		Flag1: 0b10000010,
		Flag2: 0b00000000,
		// TODO 🔥 just copied these numbers from x3270
		SDW: 0x09,
		SDH: 0x0C,
	}
}

// 🟦 Public emitter function

func (s CharacterSets) Put(in *stream.Inbound) {
	chars := []byte{
		byte(s.SFID),
		byte(s.QCode),
	}
	// 👇 flags indicating basic support
	chars = append(chars, s.Flag1)
	chars = append(chars, s.Flag2)
	chars = append(chars, s.SDW)
	chars = append(chars, s.SDH)
	// TODO 🔥 this extra is generated by x3270???
	// 00 00 00 00 07 00 10 00 02 B9 00 25 01 00 F1 03 C3 01 36
	xtra := []byte{0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x10, 0x00, 0x02, 0xB9, 0x00, 0x25, 0x01, 0x00, 0xF1, 0x03, 0xC3, 0x01, 0x36}
	chars = append(chars, xtra...)
	in.Put16(uint16(len(chars) + 2))
	in.PutSlice(chars)
}
