package qr

import (
	"encoding/binary"
	"go3270/emulator/consts"
	"go3270/emulator/stream"
)

type UsableArea struct {
	SFID   consts.SFID
	QCode  consts.QCode
	Flags1 byte
	Flags2 byte
	W      uint16
	H      uint16
}

func NewUsableArea(cols, rows int) UsableArea {
	return UsableArea{
		SFID:  consts.QUERY_REPLY,
		QCode: consts.USABLE_AREA,
		// 👇 12/14 bit addressing
		Flags1: 0b00000001,
		// 👇 dimensions in cells (not pells)
		Flags2: 0b00000000,
		W:      uint16(cols),
		H:      uint16(rows),
	}
}

func (s UsableArea) Put(in *stream.Inbound) {
	bytes := []byte{
		byte(s.SFID),
		byte(s.QCode),
	}
	// 👇 flags and data
	bytes = append(bytes, s.Flags1)
	bytes = append(bytes, s.Flags2)
	bytes = binary.BigEndian.AppendUint16(bytes, s.W)
	bytes = binary.BigEndian.AppendUint16(bytes, s.H)
	// TODO 🔥 this extra is generated by x3270???
	// 01 00 0A 02 E5 00 02 00 6F 09 0C 0A 00
	xtra := []byte{0x01, 0x00, 0x0A, 0x02, 0xE5, 0x00, 0x02, 0x00, 0x6F, 0x09, 0x0C, 0x0A, 0x00}
	bytes = append(bytes, xtra...)
	in.Put16(uint16(len(bytes) + 2))
	in.PutSlice(bytes)
}
