// Code generated by "stringer -type=Topic"; DO NOT EDIT.

package core

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[attn-0]
	_ = x[close-1]
	_ = x[focus-2]
	_ = x[keystroke-3]
	_ = x[inbound-4]
	_ = x[initialize-5]
	_ = x[outbound-6]
	_ = x[panic-7]
	_ = x[probe-8]
	_ = x[q-9]
	_ = x[ql-10]
	_ = x[rb-11]
	_ = x[render-12]
	_ = x[renderDeltas-13]
	_ = x[reset-14]
	_ = x[rm-15]
	_ = x[rma-16]
	_ = x[status-17]
	_ = x[tick-18]
	_ = x[trace-19]
	_ = x[wcchar-20]
}

const _Topic_name = "attnclosefocuskeystrokeinboundinitializeoutboundpanicprobeqqlrbrenderrenderDeltasresetrmrmastatusticktracewcchar"

var _Topic_index = [...]uint8{0, 4, 9, 14, 23, 30, 40, 48, 53, 58, 59, 61, 63, 69, 81, 86, 88, 91, 97, 101, 106, 112}

func (i Topic) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Topic_index)-1 {
		return "Topic(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Topic_name[_Topic_index[idx]:_Topic_index[idx+1]]
}
