package qr

import (
	"emulator/iface"
	"emulator/types"
)

// 🟧 Query Reply structured field

// 👁️ All page references to:
// https://bitsavers.org/pdf/ibm/3270/GA23-0059-07_3270_Data_Stream_Programmers_Reference_199206.pdf

// 👁️ Query Reply (Character Sets) pp 6-28 to 6-35

type CharacterSets struct {
	SFID  types.SFID
	QCode types.QCode
	Flag1 byte
	Flag2 byte
	SDW   byte
	SDH   byte
}

// 🟦 Constructor

func NewCharacterSets() CharacterSets {
	return CharacterSets{
		SFID:  types.QUERY_REPLY,
		QCode: types.CHARACTER_SETS,
		Flag1: 0b10000010,
		Flag2: 0b00000000,
		// TODO 🔥 just copied these numbers from x3270
		SDW: 0x09,
		SDH: 0x0c,
	}
}

// 🟦 Public emitter function

func (s CharacterSets) Put(in iface.Inbound) {
	chars := []byte{
		byte(s.SFID),
		byte(s.QCode),
	}
	// 👇 flags indicating basic support
	chars = append(chars, s.Flag1)
	chars = append(chars, s.Flag2)
	chars = append(chars, s.SDW)
	chars = append(chars, s.SDH)
	// TODO 🔥 this extra is generated by x3270???
	// 00 00 00 00 07 00 10 00 02 B9 00 25 01 00 F1 03 C3 01 36
	xtra := []byte{0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x10, 0x00, 0x02, 0xb9, 0x00, 0x25, 0x01, 0x00, 0xf1, 0x03, 0xc3, 0x01, 0x36}
	chars = append(chars, xtra...)
	in.Put16(uint16(len(chars) + 2))
	in.PutSlice(chars)
}
