package qr

import (
	"emulator/iface"
	"emulator/types"
	"encoding/binary"
)

// 🟧 Query Reply structured field

// 👁️ All page references to:
// https://bitsavers.org/pdf/ibm/3270/GA23-0059-07_3270_Data_Stream_Programmers_Reference_199206.pdf

// 👁️ Query Reply (Usable Area) pp 6-100 to 6-109

type UsableArea struct {
	SFID   types.SFID
	QCode  types.QCode
	Flags1 byte
	Flags2 byte
	W      uint16
	H      uint16
}

// 🟦 Constructor

func NewUsableArea(cols, rows uint) UsableArea {
	return UsableArea{
		SFID:  types.QUERY_REPLY,
		QCode: types.USABLE_AREA,
		// 👇 12/14 bit addressing
		Flags1: 0b00000001,
		// 👇 dimensions in cells (not pells)
		Flags2: 0b00000000,
		W:      uint16(cols),
		H:      uint16(rows),
	}
}

// 🟦 Public emitter function

func (s UsableArea) Put(in iface.Inbound) {
	chars := []byte{
		byte(s.SFID),
		byte(s.QCode),
	}
	// 👇 flags and data
	chars = append(chars, s.Flags1)
	chars = append(chars, s.Flags2)
	chars = binary.BigEndian.AppendUint16(chars, s.W)
	chars = binary.BigEndian.AppendUint16(chars, s.H)
	// TODO 🔥 this extra is generated by x3270???
	// 01 00 0a 02 e5 00 02 00 6f 09 0c 0a 00
	xtra := []byte{0x01, 0x00, 0x0a, 0x02, 0xe5, 0x00, 0x02, 0x00, 0x6f, 0x09, 0x0c, 0x0a, 0x00}
	chars = append(chars, xtra...)
	in.Put16(uint16(len(chars) + 2))
	in.PutSlice(chars)
}
